# # # # # # # #
#   K i k o   #
# # # # # # # #

# Basic
name:               "MLML Lab"
title:              "MLML Lab at Boston Chidlren's Hospital and Harvard Medical School"
description:        "The Machine Learning for Medical Language (MLML) Lab at the Computational Health Informatics Program of Boston Children's Hospital does natural language processing research with deep neural networks."


# URL
url:                https://machine-learning-for-medical-language.github.io/
baseurl:            
#baseurl:            "" #For Root Domain
permalink:          /:year/:month/:day/:title.html

# Markdown
markdown:           kramdown

# Highlighter
highlighter:        rouge

# Navigation
nav:
  - name:           "home"
    href:           "/"
  - name:           "about"
    href:           "/about"
  - name:           "publications"
    href:           "/publication"
  - name:           "people"
    href:           "/people"
  # - name:           "blog"
    # href:           "/blog"
#   - name:           "abstracts"
#     href:           "/abstracts"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
  -
    scope:
      path:         ""
      type:         "people"
    values:
      layout:       "profile"


collections:
  people:
    output: true
    permalink: /people/:title/index.html
